/*
 * Copyright 2020 Google LLC
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
/*
 * This code was generated by https://github.com/google/apis-client-generator/
 * (build: 2020-07-27 18:22:59 EDT)
 * on 2020-07-27 at 22:23:15 UTC 
 * Modify at your own risk.
 */

package com.google.api.services.businessmessages.v1.model;

/**
 * Carousel of cards.
 *
 * <p> This is the Java data model class that specifies how to parse/serialize into the JSON that is
 * transmitted over HTTP when working with the Business Messages API. For a detailed explanation
 * see:
 * <a href="https://developers.google.com/api-client-library/java/google-http-java-client/json">https://developers.google.com/api-client-library/java/google-http-java-client/json</a>
 * </p>
 *
 * @author Google, Inc.
 */
@SuppressWarnings("javadoc")
public final class BusinessMessagesCarouselCard extends com.google.api.client.json.GenericJson {

  /**
   * The list of contents for each card in the carousel. A carousel can have a minimum of 2 cards
   * and a maximum 10 cards.
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.util.List<BusinessMessagesCardContent> cardContents;

  static {
    // hack to force ProGuard to consider BusinessMessagesCardContent used, since otherwise it would be stripped out
    // see https://github.com/google/google-api-java-client/issues/543
    com.google.api.client.util.Data.nullOf(BusinessMessagesCardContent.class);
  }

  /**
   * The width of the cards in the carousel.
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String cardWidth;

  /**
   * The list of contents for each card in the carousel. A carousel can have a minimum of 2 cards
   * and a maximum 10 cards.
   * @return value or {@code null} for none
   */
  public java.util.List<BusinessMessagesCardContent> getCardContents() {
    return cardContents;
  }

  /**
   * The list of contents for each card in the carousel. A carousel can have a minimum of 2 cards
   * and a maximum 10 cards.
   * @param cardContents cardContents or {@code null} for none
   */
  public BusinessMessagesCarouselCard setCardContents(java.util.List<BusinessMessagesCardContent> cardContents) {
    this.cardContents = cardContents;
    return this;
  }

  /**
   * The width of the cards in the carousel.
   * @return value or {@code null} for none
   */
  public java.lang.String getCardWidth() {
    return cardWidth;
  }

  /**
   * The width of the cards in the carousel.
   * @param cardWidth cardWidth or {@code null} for none
   */
  public BusinessMessagesCarouselCard setCardWidth(java.lang.String cardWidth) {
    this.cardWidth = cardWidth;
    return this;
  }

  @Override
  public BusinessMessagesCarouselCard set(String fieldName, Object value) {
    return (BusinessMessagesCarouselCard) super.set(fieldName, value);
  }

  @Override
  public BusinessMessagesCarouselCard clone() {
    return (BusinessMessagesCarouselCard) super.clone();
  }

}
