/*
 * Copyright 2020 Google LLC
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
/*
 * This code was generated by https://github.com/google/apis-client-generator/
 * (build: 2020-07-27 18:22:59 EDT)
 * on 2020-07-27 at 22:23:15 UTC 
 * Modify at your own risk.
 */

package com.google.api.services.businessmessages.v1.model;

/**
 * A media file within a rich card.
 *
 * <p> This is the Java data model class that specifies how to parse/serialize into the JSON that is
 * transmitted over HTTP when working with the Business Messages API. For a detailed explanation
 * see:
 * <a href="https://developers.google.com/api-client-library/java/google-http-java-client/json">https://developers.google.com/api-client-library/java/google-http-java-client/json</a>
 * </p>
 *
 * @author Google, Inc.
 */
@SuppressWarnings("javadoc")
public final class BusinessMessagesMedia extends com.google.api.client.json.GenericJson {

  /**
   * Information about a file, including the URL of the file and the URL of the file's thumbnail.
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private BusinessMessagesContentInfo contentInfo;

  /**
   * The height of the media within a rich card.
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String height;

  /**
   * Information about a file, including the URL of the file and the URL of the file's thumbnail.
   * @return value or {@code null} for none
   */
  public BusinessMessagesContentInfo getContentInfo() {
    return contentInfo;
  }

  /**
   * Information about a file, including the URL of the file and the URL of the file's thumbnail.
   * @param contentInfo contentInfo or {@code null} for none
   */
  public BusinessMessagesMedia setContentInfo(BusinessMessagesContentInfo contentInfo) {
    this.contentInfo = contentInfo;
    return this;
  }

  /**
   * The height of the media within a rich card.
   * @return value or {@code null} for none
   */
  public java.lang.String getHeight() {
    return height;
  }

  /**
   * The height of the media within a rich card.
   * @param height height or {@code null} for none
   */
  public BusinessMessagesMedia setHeight(java.lang.String height) {
    this.height = height;
    return this;
  }

  @Override
  public BusinessMessagesMedia set(String fieldName, Object value) {
    return (BusinessMessagesMedia) super.set(fieldName, value);
  }

  @Override
  public BusinessMessagesMedia clone() {
    return (BusinessMessagesMedia) super.clone();
  }

}
