/*
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except
 * in compliance with the License. You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the License
 * is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
 * or implied. See the License for the specific language governing permissions and limitations under
 * the License.
 */
/*
 * This code was generated by https://github.com/google/apis-client-generator/
 * (build: 2022-02-10 02:07:51 UTC)
 * on 2022-02-10 at 02:08:18 UTC 
 * Modify at your own risk.
 */

package com.google.api.services.businessmessages.v1.model;

/**
 * Details about the representative (human or chatbot) that sent the message.
 *
 * <p> This is the Java data model class that specifies how to parse/serialize into the JSON that is
 * transmitted over HTTP when working with the Business Messages API. For a detailed explanation
 * see:
 * <a href="https://developers.google.com/api-client-library/java/google-http-java-client/json">https://developers.google.com/api-client-library/java/google-http-java-client/json</a>
 * </p>
 *
 * @author Google, Inc.
 */
@SuppressWarnings("javadoc")
public final class BusinessMessagesRepresentative extends com.google.api.client.json.GenericJson {

  /**
   * Optional. The representative's avatar image, as a publicly available URL. Displays as a circle.
   * Avatar images don't support personal information, such as depictions of representatives in
   * photographs or illustrations. Use images that don't identify individuals, such as icons, logos,
   * or fictitious illustrations. After an avatar image is used in a message, the image can't be
   * modified or deleted. Images must be 1024x1024 px and have a maximum files size of 50 KB.
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String avatarImage;

  /**
   * Optional. Name of the representative.
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String displayName;

  /**
   * Required. The type of representative.
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String representativeType;

  /**
   * Optional. The representative's avatar image, as a publicly available URL. Displays as a circle.
   * Avatar images don't support personal information, such as depictions of representatives in
   * photographs or illustrations. Use images that don't identify individuals, such as icons, logos,
   * or fictitious illustrations. After an avatar image is used in a message, the image can't be
   * modified or deleted. Images must be 1024x1024 px and have a maximum files size of 50 KB.
   * @return value or {@code null} for none
   */
  public java.lang.String getAvatarImage() {
    return avatarImage;
  }

  /**
   * Optional. The representative's avatar image, as a publicly available URL. Displays as a circle.
   * Avatar images don't support personal information, such as depictions of representatives in
   * photographs or illustrations. Use images that don't identify individuals, such as icons, logos,
   * or fictitious illustrations. After an avatar image is used in a message, the image can't be
   * modified or deleted. Images must be 1024x1024 px and have a maximum files size of 50 KB.
   * @param avatarImage avatarImage or {@code null} for none
   */
  public BusinessMessagesRepresentative setAvatarImage(java.lang.String avatarImage) {
    this.avatarImage = avatarImage;
    return this;
  }

  /**
   * Optional. Name of the representative.
   * @return value or {@code null} for none
   */
  public java.lang.String getDisplayName() {
    return displayName;
  }

  /**
   * Optional. Name of the representative.
   * @param displayName displayName or {@code null} for none
   */
  public BusinessMessagesRepresentative setDisplayName(java.lang.String displayName) {
    this.displayName = displayName;
    return this;
  }

  /**
   * Required. The type of representative.
   * @return value or {@code null} for none
   */
  public java.lang.String getRepresentativeType() {
    return representativeType;
  }

  /**
   * Required. The type of representative.
   * @param representativeType representativeType or {@code null} for none
   */
  public BusinessMessagesRepresentative setRepresentativeType(java.lang.String representativeType) {
    this.representativeType = representativeType;
    return this;
  }

  @Override
  public BusinessMessagesRepresentative set(String fieldName, Object value) {
    return (BusinessMessagesRepresentative) super.set(fieldName, value);
  }

  @Override
  public BusinessMessagesRepresentative clone() {
    return (BusinessMessagesRepresentative) super.clone();
  }

}
