/*
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except
 * in compliance with the License. You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the License
 * is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
 * or implied. See the License for the specific language governing permissions and limitations under
 * the License.
 */
/*
 * This code was generated by https://github.com/google/apis-client-generator/
 * (build: 2020-11-11 13:17:14 EST)
 * on 2020-11-11 at 18:17:15 UTC 
 * Modify at your own risk.
 */

package com.google.api.services.businessmessages.v1.model;

/**
 * When tapped, initiates the corresponding native action on the device.
 *
 * <p> This is the Java data model class that specifies how to parse/serialize into the JSON that is
 * transmitted over HTTP when working with the Business Messages API. For a detailed explanation
 * see:
 * <a href="https://developers.google.com/api-client-library/java/google-http-java-client/json">https://developers.google.com/api-client-library/java/google-http-java-client/json</a>
 * </p>
 *
 * @author Google, Inc.
 */
@SuppressWarnings("javadoc")
public final class BusinessMessagesSuggestedAction extends com.google.api.client.json.GenericJson {

  /**
   * Opens the user's default dialer app.
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private BusinessMessagesDialAction dialAction;

  /**
   * Opens the specified URL.
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private BusinessMessagesOpenUrlAction openUrlAction;

  /**
   * The string that the agent receives when a user taps the suggested action.
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String postbackData;

  /**
   * Text that is shown in the suggested action. Maximum 25 characters.
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String text;

  /**
   * Opens the user's default dialer app.
   * @return value or {@code null} for none
   */
  public BusinessMessagesDialAction getDialAction() {
    return dialAction;
  }

  /**
   * Opens the user's default dialer app.
   * @param dialAction dialAction or {@code null} for none
   */
  public BusinessMessagesSuggestedAction setDialAction(BusinessMessagesDialAction dialAction) {
    this.dialAction = dialAction;
    return this;
  }

  /**
   * Opens the specified URL.
   * @return value or {@code null} for none
   */
  public BusinessMessagesOpenUrlAction getOpenUrlAction() {
    return openUrlAction;
  }

  /**
   * Opens the specified URL.
   * @param openUrlAction openUrlAction or {@code null} for none
   */
  public BusinessMessagesSuggestedAction setOpenUrlAction(BusinessMessagesOpenUrlAction openUrlAction) {
    this.openUrlAction = openUrlAction;
    return this;
  }

  /**
   * The string that the agent receives when a user taps the suggested action.
   * @return value or {@code null} for none
   */
  public java.lang.String getPostbackData() {
    return postbackData;
  }

  /**
   * The string that the agent receives when a user taps the suggested action.
   * @param postbackData postbackData or {@code null} for none
   */
  public BusinessMessagesSuggestedAction setPostbackData(java.lang.String postbackData) {
    this.postbackData = postbackData;
    return this;
  }

  /**
   * Text that is shown in the suggested action. Maximum 25 characters.
   * @return value or {@code null} for none
   */
  public java.lang.String getText() {
    return text;
  }

  /**
   * Text that is shown in the suggested action. Maximum 25 characters.
   * @param text text or {@code null} for none
   */
  public BusinessMessagesSuggestedAction setText(java.lang.String text) {
    this.text = text;
    return this;
  }

  @Override
  public BusinessMessagesSuggestedAction set(String fieldName, Object value) {
    return (BusinessMessagesSuggestedAction) super.set(fieldName, value);
  }

  @Override
  public BusinessMessagesSuggestedAction clone() {
    return (BusinessMessagesSuggestedAction) super.clone();
  }

}
