/*
 * Copyright 2020 Google LLC
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
/*
 * This code was generated by https://github.com/google/apis-client-generator/
 * (build: 2020-07-27 18:22:59 EDT)
 * on 2020-07-27 at 22:23:15 UTC 
 * Modify at your own risk.
 */

package com.google.api.services.businessmessages.v1.model;

/**
 * Card content.
 *
 * <p> This is the Java data model class that specifies how to parse/serialize into the JSON that is
 * transmitted over HTTP when working with the Business Messages API. For a detailed explanation
 * see:
 * <a href="https://developers.google.com/api-client-library/java/google-http-java-client/json">https://developers.google.com/api-client-library/java/google-http-java-client/json</a>
 * </p>
 *
 * @author Google, Inc.
 */
@SuppressWarnings("javadoc")
public final class BusinessMessagesCardContent extends com.google.api.client.json.GenericJson {

  /**
   * Optional. Description of the card. Maximum 2000 characters.
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String description;

  /**
   * Optional. Media to include in the card.
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private BusinessMessagesMedia media;

  /**
   * Optional. List of suggestions to include in the card. Maximum 4 suggestions.
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.util.List<BusinessMessagesSuggestion> suggestions;

  /**
   * Optional. Title of the card. Maximum 200 characters.
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String title;

  /**
   * Optional. Description of the card. Maximum 2000 characters.
   * @return value or {@code null} for none
   */
  public java.lang.String getDescription() {
    return description;
  }

  /**
   * Optional. Description of the card. Maximum 2000 characters.
   * @param description description or {@code null} for none
   */
  public BusinessMessagesCardContent setDescription(java.lang.String description) {
    this.description = description;
    return this;
  }

  /**
   * Optional. Media to include in the card.
   * @return value or {@code null} for none
   */
  public BusinessMessagesMedia getMedia() {
    return media;
  }

  /**
   * Optional. Media to include in the card.
   * @param media media or {@code null} for none
   */
  public BusinessMessagesCardContent setMedia(BusinessMessagesMedia media) {
    this.media = media;
    return this;
  }

  /**
   * Optional. List of suggestions to include in the card. Maximum 4 suggestions.
   * @return value or {@code null} for none
   */
  public java.util.List<BusinessMessagesSuggestion> getSuggestions() {
    return suggestions;
  }

  /**
   * Optional. List of suggestions to include in the card. Maximum 4 suggestions.
   * @param suggestions suggestions or {@code null} for none
   */
  public BusinessMessagesCardContent setSuggestions(java.util.List<BusinessMessagesSuggestion> suggestions) {
    this.suggestions = suggestions;
    return this;
  }

  /**
   * Optional. Title of the card. Maximum 200 characters.
   * @return value or {@code null} for none
   */
  public java.lang.String getTitle() {
    return title;
  }

  /**
   * Optional. Title of the card. Maximum 200 characters.
   * @param title title or {@code null} for none
   */
  public BusinessMessagesCardContent setTitle(java.lang.String title) {
    this.title = title;
    return this;
  }

  @Override
  public BusinessMessagesCardContent set(String fieldName, Object value) {
    return (BusinessMessagesCardContent) super.set(fieldName, value);
  }

  @Override
  public BusinessMessagesCardContent clone() {
    return (BusinessMessagesCardContent) super.clone();
  }

}
