/*
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except
 * in compliance with the License. You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the License
 * is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
 * or implied. See the License for the specific language governing permissions and limitations under
 * the License.
 */
/*
 * This code was generated by https://github.com/google/apis-client-generator/
 * (build: 2022-02-10 02:07:51 UTC)
 * on 2022-02-10 at 02:08:18 UTC 
 * Modify at your own risk.
 */

package com.google.api.services.businessmessages.v1.model;

/**
 * When tapped, sends the text reply back to the agent.
 *
 * <p> This is the Java data model class that specifies how to parse/serialize into the JSON that is
 * transmitted over HTTP when working with the Business Messages API. For a detailed explanation
 * see:
 * <a href="https://developers.google.com/api-client-library/java/google-http-java-client/json">https://developers.google.com/api-client-library/java/google-http-java-client/json</a>
 * </p>
 *
 * @author Google, Inc.
 */
@SuppressWarnings("javadoc")
public final class BusinessMessagesSuggestedReply extends com.google.api.client.json.GenericJson {

  /**
   * The string that the agent receives when a user taps the suggested reply. Maximum 2,048
   * characters.
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String postbackData;

  /**
   * Text that is shown in the suggested reply and sent to the agent when the user taps it. Maximum
   * 25 characters.
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String text;

  /**
   * The string that the agent receives when a user taps the suggested reply. Maximum 2,048
   * characters.
   * @return value or {@code null} for none
   */
  public java.lang.String getPostbackData() {
    return postbackData;
  }

  /**
   * The string that the agent receives when a user taps the suggested reply. Maximum 2,048
   * characters.
   * @param postbackData postbackData or {@code null} for none
   */
  public BusinessMessagesSuggestedReply setPostbackData(java.lang.String postbackData) {
    this.postbackData = postbackData;
    return this;
  }

  /**
   * Text that is shown in the suggested reply and sent to the agent when the user taps it. Maximum
   * 25 characters.
   * @return value or {@code null} for none
   */
  public java.lang.String getText() {
    return text;
  }

  /**
   * Text that is shown in the suggested reply and sent to the agent when the user taps it. Maximum
   * 25 characters.
   * @param text text or {@code null} for none
   */
  public BusinessMessagesSuggestedReply setText(java.lang.String text) {
    this.text = text;
    return this;
  }

  @Override
  public BusinessMessagesSuggestedReply set(String fieldName, Object value) {
    return (BusinessMessagesSuggestedReply) super.set(fieldName, value);
  }

  @Override
  public BusinessMessagesSuggestedReply clone() {
    return (BusinessMessagesSuggestedReply) super.clone();
  }

}
