/*
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except
 * in compliance with the License. You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the License
 * is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
 * or implied. See the License for the specific language governing permissions and limitations under
 * the License.
 */
/*
 * This code was generated by https://github.com/google/apis-client-generator/
 * (build: 2022-02-10 02:07:51 UTC)
 * on 2022-02-10 at 02:08:18 UTC 
 * Modify at your own risk.
 */

package com.google.api.services.businessmessages.v1.model;

/**
 * A receipt of the message.
 *
 * <p> This is the Java data model class that specifies how to parse/serialize into the JSON that is
 * transmitted over HTTP when working with the Business Messages API. For a detailed explanation
 * see:
 * <a href="https://developers.google.com/api-client-library/java/google-http-java-client/json">https://developers.google.com/api-client-library/java/google-http-java-client/json</a>
 * </p>
 *
 * @author Google, Inc.
 */
@SuppressWarnings("javadoc")
public final class BusinessMessagesReceipt extends com.google.api.client.json.GenericJson {

  /**
   * The name of the receipt, as set by Business Messages. Resolves to
   * "conversations/{conversationId}/messages/{messageId}/receipt", where {conversationId} is the
   * unique ID for the conversation and {messageId} is the unique ID for the message.
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String name;

  /**
   * A receipt type.
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String receiptType;

  /**
   * The name of the receipt, as set by Business Messages. Resolves to
   * "conversations/{conversationId}/messages/{messageId}/receipt", where {conversationId} is the
   * unique ID for the conversation and {messageId} is the unique ID for the message.
   * @return value or {@code null} for none
   */
  public java.lang.String getName() {
    return name;
  }

  /**
   * The name of the receipt, as set by Business Messages. Resolves to
   * "conversations/{conversationId}/messages/{messageId}/receipt", where {conversationId} is the
   * unique ID for the conversation and {messageId} is the unique ID for the message.
   * @param name name or {@code null} for none
   */
  public BusinessMessagesReceipt setName(java.lang.String name) {
    this.name = name;
    return this;
  }

  /**
   * A receipt type.
   * @return value or {@code null} for none
   */
  public java.lang.String getReceiptType() {
    return receiptType;
  }

  /**
   * A receipt type.
   * @param receiptType receiptType or {@code null} for none
   */
  public BusinessMessagesReceipt setReceiptType(java.lang.String receiptType) {
    this.receiptType = receiptType;
    return this;
  }

  @Override
  public BusinessMessagesReceipt set(String fieldName, Object value) {
    return (BusinessMessagesReceipt) super.set(fieldName, value);
  }

  @Override
  public BusinessMessagesReceipt clone() {
    return (BusinessMessagesReceipt) super.clone();
  }

}
