/*
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except
 * in compliance with the License. You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the License
 * is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
 * or implied. See the License for the specific language governing permissions and limitations under
 * the License.
 */
/*
 * This code was generated by https://github.com/google/apis-client-generator/
 * (build: 2021-01-14 21:39:54 UTC)
 * on 2021-01-14 at 21:40:20 UTC 
 * Modify at your own risk.
 */

package com.google.api.services.businessmessages.v1.model;

/**
 * Details for authentication via OAuth.
 *
 * <p> This is the Java data model class that specifies how to parse/serialize into the JSON that is
 * transmitted over HTTP when working with the Business Messages API. For a detailed explanation
 * see:
 * <a href="https://developers.google.com/api-client-library/java/google-http-java-client/json">https://developers.google.com/api-client-library/java/google-http-java-client/json</a>
 * </p>
 *
 * @author Google, Inc.
 */
@SuppressWarnings("javadoc")
public final class BusinessMessagesAuthenticationRequestOauth extends com.google.api.client.json.GenericJson {

  /**
   * Required. The [ID](https://www.oauth.com/oauth2-servers/client-registration/client-id-secret/)
   * of the application that asks for authorization.
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String clientId;

  /**
   * Required. The [code challenge](https://tools.ietf.org/html/rfc7636#section-4.2) used to
   * exchange access tokens.
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String codeChallenge;

  /**
   * Required. An array that specifies the [scopes](https://oauth.net/2/scope/) of the request.
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.util.List<java.lang.String> scopes;

  /**
   * Required. The [ID](https://www.oauth.com/oauth2-servers/client-registration/client-id-secret/)
   * of the application that asks for authorization.
   * @return value or {@code null} for none
   */
  public java.lang.String getClientId() {
    return clientId;
  }

  /**
   * Required. The [ID](https://www.oauth.com/oauth2-servers/client-registration/client-id-secret/)
   * of the application that asks for authorization.
   * @param clientId clientId or {@code null} for none
   */
  public BusinessMessagesAuthenticationRequestOauth setClientId(java.lang.String clientId) {
    this.clientId = clientId;
    return this;
  }

  /**
   * Required. The [code challenge](https://tools.ietf.org/html/rfc7636#section-4.2) used to
   * exchange access tokens.
   * @return value or {@code null} for none
   */
  public java.lang.String getCodeChallenge() {
    return codeChallenge;
  }

  /**
   * Required. The [code challenge](https://tools.ietf.org/html/rfc7636#section-4.2) used to
   * exchange access tokens.
   * @param codeChallenge codeChallenge or {@code null} for none
   */
  public BusinessMessagesAuthenticationRequestOauth setCodeChallenge(java.lang.String codeChallenge) {
    this.codeChallenge = codeChallenge;
    return this;
  }

  /**
   * Required. An array that specifies the [scopes](https://oauth.net/2/scope/) of the request.
   * @return value or {@code null} for none
   */
  public java.util.List<java.lang.String> getScopes() {
    return scopes;
  }

  /**
   * Required. An array that specifies the [scopes](https://oauth.net/2/scope/) of the request.
   * @param scopes scopes or {@code null} for none
   */
  public BusinessMessagesAuthenticationRequestOauth setScopes(java.util.List<java.lang.String> scopes) {
    this.scopes = scopes;
    return this;
  }

  @Override
  public BusinessMessagesAuthenticationRequestOauth set(String fieldName, Object value) {
    return (BusinessMessagesAuthenticationRequestOauth) super.set(fieldName, value);
  }

  @Override
  public BusinessMessagesAuthenticationRequestOauth clone() {
    return (BusinessMessagesAuthenticationRequestOauth) super.clone();
  }

}
