/*
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except
 * in compliance with the License. You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the License
 * is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
 * or implied. See the License for the specific language governing permissions and limitations under
 * the License.
 */
/*
 * This code was generated by https://github.com/google/apis-client-generator/
 * (build: 2020-11-23 12:43:28 EST)
 * on 2020-11-23 at 17:43:39 UTC 
 * Modify at your own risk.
 */

package com.google.api.services.businessmessages.v1.model;

/**
 * A survey to measure customer satisfaction.
 *
 * <p> This is the Java data model class that specifies how to parse/serialize into the JSON that is
 * transmitted over HTTP when working with the Business Messages API. For a detailed explanation
 * see:
 * <a href="https://developers.google.com/api-client-library/java/google-http-java-client/json">https://developers.google.com/api-client-library/java/google-http-java-client/json</a>
 * </p>
 *
 * @author Google, Inc.
 */
@SuppressWarnings("javadoc")
public final class BusinessMessagesSurvey extends com.google.api.client.json.GenericJson {

  /**
   * The name of the survey, as set by Business Messages. Resolves to
   * "conversations/{conversationId}/surveys/{surveyId}", where {conversationId} is the unique ID
   * for the conversation and {surveyId} is the unique ID for the survey.
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String name;

  /**
   * The name of the survey, as set by Business Messages. Resolves to
   * "conversations/{conversationId}/surveys/{surveyId}", where {conversationId} is the unique ID
   * for the conversation and {surveyId} is the unique ID for the survey.
   * @return value or {@code null} for none
   */
  public java.lang.String getName() {
    return name;
  }

  /**
   * The name of the survey, as set by Business Messages. Resolves to
   * "conversations/{conversationId}/surveys/{surveyId}", where {conversationId} is the unique ID
   * for the conversation and {surveyId} is the unique ID for the survey.
   * @param name name or {@code null} for none
   */
  public BusinessMessagesSurvey setName(java.lang.String name) {
    this.name = name;
    return this;
  }

  @Override
  public BusinessMessagesSurvey set(String fieldName, Object value) {
    return (BusinessMessagesSurvey) super.set(fieldName, value);
  }

  @Override
  public BusinessMessagesSurvey clone() {
    return (BusinessMessagesSurvey) super.clone();
  }

}
