/*
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except
 * in compliance with the License. You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the License
 * is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
 * or implied. See the License for the specific language governing permissions and limitations under
 * the License.
 */
/*
 * This code was generated by https://github.com/google/apis-client-generator/
 * (build: 2020-11-23 12:43:28 EST)
 * on 2020-11-23 at 17:43:39 UTC 
 * Modify at your own risk.
 */

package com.google.api.services.businessmessages.v1.model;

/**
 * Standalone card.
 *
 * <p> This is the Java data model class that specifies how to parse/serialize into the JSON that is
 * transmitted over HTTP when working with the Business Messages API. For a detailed explanation
 * see:
 * <a href="https://developers.google.com/api-client-library/java/google-http-java-client/json">https://developers.google.com/api-client-library/java/google-http-java-client/json</a>
 * </p>
 *
 * @author Google, Inc.
 */
@SuppressWarnings("javadoc")
public final class BusinessMessagesStandaloneCard extends com.google.api.client.json.GenericJson {

  /**
   * Card content.
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private BusinessMessagesCardContent cardContent;

  /**
   * Card content.
   * @return value or {@code null} for none
   */
  public BusinessMessagesCardContent getCardContent() {
    return cardContent;
  }

  /**
   * Card content.
   * @param cardContent cardContent or {@code null} for none
   */
  public BusinessMessagesStandaloneCard setCardContent(BusinessMessagesCardContent cardContent) {
    this.cardContent = cardContent;
    return this;
  }

  @Override
  public BusinessMessagesStandaloneCard set(String fieldName, Object value) {
    return (BusinessMessagesStandaloneCard) super.set(fieldName, value);
  }

  @Override
  public BusinessMessagesStandaloneCard clone() {
    return (BusinessMessagesStandaloneCard) super.clone();
  }

}
